exclude_path = [
    "public/2015/",
    "public/2016/",
    "public/2017/",
    "public/2018/",
    "public/2019/",
    "public/2023/",
    "public/2024/",
    "public/images/icons/flaticon.html",
]

base = "public"